server:
  port: 8000

eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

# @author:jaemin - route, filter 설정
spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      # cors 설정
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # SCG를 호출하는 web Client 주
            allowedMethods: # SCG에서 허용하는 methods
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
            allowedHeaders: '*' # SCG에서 허용하는 Headers
            allow-credentials: true
#      default-filters:
#        filters:
#          - name: LoggingFilter
#            args:
#              baseMessage: Start Logging Filter.
#              preLogger: true
#              postLogger: true
      routes:
        # User Service 시작
        # 로그인, 회원가입, 중복체크
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/v1/logins, /user-service/users/v1/join, /user-service/users/v1/owner/join, /user-service/managers/validate, /user-service/managers/status, /user-service/users/v1/validation/**, /user-service/api/v1/info/
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # user-service의 모든 요청 filter처리
        # 회원정보, 로그아웃
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users/v1/mypage/**,/user-service/users/v1/logout, /user-service/users/v1/refresh
            - Method=PATCH,DELETE,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthentication
              args:
                roles: ROLE_USER, ROLE_MANAGER
        # User Service 끝
        # Item Service 시작
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/items/v1/owner/**
            - Method=GET,PATCH,DELETE,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/item-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthentication
              args:
                roles: ROLE_MANAGER
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/items/v1/stores/**, /item-service/items/v1/item/**, /item-service/items/v1/search/**
            - Method=GET,PATCH,DELETE,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/item-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthentication
              args:
                roles: ROLE_USER, ROLE_MANAGER
        - id: item-service
          uri: lb://ITEM-SERVICE
          predicates:
            - Path=/item-service/items/v1/**
            - Method=GET,PATCH,DELETE,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/item-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthentication
              args:
                roles: ROLE_USER, ROLE_MANAGER
        # Order Service 시작
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/orders/v1/**
            - Method=GET,PATCH,DELETE,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
            - name: JwtAuthentication
              args:
                roles: ROLE_USER, ROLE_MANAGER
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/swagger-ui/, /v2/api-docs, /configuration/**, /swagger*/**, /webjars/**
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie
##            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        # config 서비스
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/actuator/**
#            - Method=GET,POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        # config 서비스
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/health_check
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

# gw process 추적
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
