server:
  port: 8888

spring:
  application:
    name: config-service
#  rabbitmq:
#    host:
#    port:
#    username:
#    password:
#  profiles:
#    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AtTheFoodTruck/config-management.git
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
